### ISSUE TITLE
zoom failing checksum

### ISSUE THREAD

**Issue by jacktose** [mikecole/chocolatey-packages#69]
zoom 4.8.5336.0928 fails install because of checksum mismatch. CLI output below. Full log available if desired.
This has been noted by others on [the package chat](https://chocolatey.org/packages/zoom#package-discussion).
Possibly related to #34.

```
PS C:\WINDOWS\system32> choco upgrade zoom
Chocolatey v0.10.15
Upgrading the following packages:
zoom
By upgrading you accept licenses for the packages.

You have zoom v4.5.3372.0908 installed. Version 4.8.5336.0928 is available based on your source(s).
Progress: Downloading zoom 4.8.5336.0928... 100%

zoom v4.8.5336.0928 [Approved]
zoom package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'CD787D65A6A4C4FACD0C4C99E2CBF957E78DBB36482AF341FDA2ACF2B19B738B'.
Downloading zoom
  from 'https://zoom.us/client/latest/ZoomInstallerFull.msi'
Progress: 100% - Completed download of C:\Users\jacktose\AppData\Local\Temp\chocolatey\zoom\4.8.5336.0928\ZoomInstallerFull.msi (24.54 MB).
Download of ZoomInstallerFull.msi (24.54 MB) completed.
Error - hashes do not match. Actual value was 'CD787D65A6A4C4FACD0C4C99E2CBF957E78DBB36482AF341FDA2ACF2B19B738B'.
ERROR: Checksum for 'C:\Users\jacktose\AppData\Local\Temp\chocolatey\zoom\4.8.5336.0928\ZoomInstallerFull.msi' did not meet 'f01bbb214abbd6689898c412f77514f91f5a0099643d30a25cd8446525a1cdab' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of zoom was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - zoom (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by camerongoodman** [comment]
still failing

**Comment by willfong** [comment]
Hi, just wondering. Looking at https://zoom.us/download#client_4meeting, it seems like the latest version is "4.5.4 (5422.0930)", lower than 4.8.5336.0928. Did I miss something here?

**Comment by GregDThomas** [comment]
4.8.5336.0928 is the version of the Zoom Plugin for Microsoft Outlook.
4.5.4 (5422.0930) is the version of the Zoom Client for Meetings

It looks to me like a little bit of confusion in the packaging - i.e. the outlook plugin is being confused with the standard client.

**Comment by mikecole** [comment]
Thanks for the issue. I had the automated updater scraping the zoom site looking for version changes. They unexpectedly updated their site, which caused my updater to grab the second version and submit a packaged update with that version. I just manually pushed a fix to the broken package. Not 100% sure what to do to get the versioning back on track. Will need to speak with choco mods. Thanks for your patience.

**Comment by mikecole** [comment]
Will keep this issue open until the version issue is addressed.

**Comment by meek2100** [comment]
Looks like this is still an issue. Here is what I'm getting on a new install attempt.

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '1702F6FE56C613C173DE289008B548B432BE4CDC57D5774A600E044B2BCF0C7A'.
Downloading zoom
  from 'https://zoom.us/client/latest/ZoomInstallerFull.msi'
Progress: 100% - Completed download of C:\Users\username\AppData\Local\Temp\chocolatey\zoom\4.8.5336.0929\ZoomInstallerFull.msi (24.54 MB).
Download of ZoomInstallerFull.msi (24.54 MB) completed.
Error - hashes do not match. Actual value was '1702F6FE56C613C173DE289008B548B432BE4CDC57D5774A600E044B2BCF0C7A'.
ERROR: Checksum for 'C:\Users\username\AppData\Local\Temp\chocolatey\zoom\4.8.5336.0929\ZoomInstallerFull.msi' did not meet 'CD787D65A6A4C4FACD0C4C99E2CBF957E78DBB36482AF341FDA2ACF2B19B738B' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of zoom was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - zoom (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\zoom\tools\chocolateyInstall.ps1'.
 See log for details.
