### ISSUE TITLE
Postgresql migration to majkinetors repository

### ISSUE THREAD

**Issue by majkinetor** [mikecole/chocolatey-packages#70]
I am taking maintenance on all postgresql packages.

I will create AU streams for postgresql and tidy up installer.

**Comment by majkinetor** [comment]
All versions updated, report is here:

https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1/bb02b270704a8a866506a054c05d6d3472362f7b#postgresql11

You can close this one too:

* https://github.com/mikecole/chocolatey-packages/issues/15

**Comment by majkinetor** [comment]
All packages failed verification while work locally here.

Do you have any insights ?

```
 ERROR: Running ["C:\Users\Administrator\AppData\Local\Temp\chocolatey\postgresql11\11.5\postgresql-11.5-2-windows-x64.exe" --install_runtimes 0 --serverport 5432 --unattendedmodeui none --superpassword ff385a4e372149c59a705018e8020d57 --enable_acledit 1 --mode unattended ] was not successful. Exit code was '1'. See log for possible error messages.
 at Start-ChocolateyProcessAsAdmin, C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1: line 324
at Install-ChocolateyInstallPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyInstallPackage.ps1: line 335
at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 408
at <ScriptBlock>, C:\ProgramData\chocolatey\lib\postgresql11\tools\chocolateyInstall.ps1: line 32
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 49
at <ScriptBlock>, <No file>: line 1
```
- [11](https://gist.github.com/choco-bot/19c574957045f6f7da6f9c2309b0b049)
- [10](https://gist.github.com/choco-bot/4ceb8d4705cd64b6345907dbc5effa75)
- [9](https://gist.github.com/choco-bot/e0e64cb9fd4daabb3cdefd43d5cbcf39)

**Comment by majkinetor** [comment]
Maybe `--install_runtimes 0` should be 1.

**Comment by mikecole** [comment]
Hope that worked. To be honest I inherited a working install script, so I never had to troubleshoot it. I then tried to create 11 from scratch and could never get it to work.

**Comment by majkinetor** [comment]
Nah, that is even worst. 

But found out what seems to be the problem:
https://github.com/majkinetor/au-packages/issues/122#issuecomment-538353838
