### ISSUE TITLE
stickies checksum wrong

### ISSUE THREAD

**Issue by robertparkerx** [mikecole/chocolatey-packages#91]
I can not upgrade stickies package because 'ERROR: Checksum for 'C:\path\to\Stickies\10.0.0.0\stickies_setup_10_0b.exe' did not meet '6F17C14C63FC269F28E5C374F6BA55F4AF1274D9684BA58F70E62DBB9BE6D1FD' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.'

**Comment by mikecole** [comment]
I just checked out the latest v10 posted on the Zhorn Software website, and Windows detected a trojan horse when downloading. This did not happen when I pushed the initial v10 package, so I suspect something malicious happened. I am currently in the process of fixing v9 and just pushed a v9.0.5.1 package, and unlisted v10. I recommend going that route. Thanks for letting me know about the issues with the package.
